# Generated by Django 4.2.7 on 2023-11-30 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_deliveredorders"),
    ]

    operations = [
        migrations.RenameField(
            model_name="medicines",
            old_name="medicine_descripton",
            new_name="medicine_description",
        ),
        migrations.RenameField(
            model_name="productitems",
            old_name="prod_descripton",
            new_name="prod_description",
        ),
    ]
